// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiuipmouolaqqpcngacv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppdWlwbW91b2xhcXFwY25nYWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTk4MTgsImV4cCI6MjA2MjgzNTgxOH0.TmhQusjdYk-DiXL96QV2z28dQKgjRZhEKs6OaYFG4CA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);